version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'  # Adjust this if your backend runs on a different port
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/your-database
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - '3000:80'
    volumes:
      - ./client:/app
    depends_on:
      - backend

  mongo:
    image: mongo:4.2
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: